# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Understanding Messy Time Series Data [Gear-Up]
author: Software and Services for Data Science (SSDS) at Stanford Libraries
copyright: "2022-2023"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Enable HTML-style image code: 
parse:
  myst_enable_extensions:
    - html_image

# Information about where the book exists on the web
repository:
  url: https://github.com/roflauren-roflauren/GearUp-MessyData  # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)
  # path_to_book: docs

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  thebe: true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
